export interface District {
  id: string;
  name: string;
  state: string;
}

export interface State {
  id: string;
  name: string;
  districts: District[];
}

export const INDIAN_STATES_DISTRICTS: State[] = [
  {
    id: "andhra-pradesh",
    name: "Andhra Pradesh",
    districts: [
      { id: "anantapur", name: "Anantapur", state: "Andhra Pradesh" },
      { id: "chittoor", name: "Chittoor", state: "Andhra Pradesh" },
      { id: "east-godavari", name: "East Godavari", state: "Andhra Pradesh" },
      { id: "guntur", name: "Guntur", state: "Andhra Pradesh" },
      { id: "krishna", name: "Krishna", state: "Andhra Pradesh" },
      { id: "kurnool", name: "Kurnool", state: "Andhra Pradesh" },
      { id: "nellore", name: "Nellore", state: "Andhra Pradesh" },
      { id: "prakasam", name: "Prakasam", state: "Andhra Pradesh" },
      { id: "srikakulam", name: "Srikakulam", state: "Andhra Pradesh" },
      { id: "visakhapatnam", name: "Visakhapatnam", state: "Andhra Pradesh" },
      { id: "vizianagaram", name: "Vizianagaram", state: "Andhra Pradesh" },
      { id: "west-godavari", name: "West Godavari", state: "Andhra Pradesh" },
      { id: "kadapa", name: "Kadapa", state: "Andhra Pradesh" }
    ]
  },
  {
    id: "arunachal-pradesh",
    name: "Arunachal Pradesh",
    districts: [
      { id: "anjaw", name: "Anjaw", state: "Arunachal Pradesh" },
      { id: "changlang", name: "Changlang", state: "Arunachal Pradesh" },
      { id: "dibang-valley", name: "Dibang Valley", state: "Arunachal Pradesh" },
      { id: "east-kameng", name: "East Kameng", state: "Arunachal Pradesh" },
      { id: "east-siang", name: "East Siang", state: "Arunachal Pradesh" },
      { id: "kamle", name: "Kamle", state: "Arunachal Pradesh" },
      { id: "kra-daadi", name: "Kra Daadi", state: "Arunachal Pradesh" },
      { id: "kurung-kumey", name: "Kurung Kumey", state: "Arunachal Pradesh" },
      { id: "lepa-rada", name: "Lepa Rada", state: "Arunachal Pradesh" },
      { id: "lohit", name: "Lohit", state: "Arunachal Pradesh" },
      { id: "longding", name: "Longding", state: "Arunachal Pradesh" },
      { id: "lower-dibang-valley", name: "Lower Dibang Valley", state: "Arunachal Pradesh" },
      { id: "lower-siang", name: "Lower Siang", state: "Arunachal Pradesh" },
      { id: "lower-subansiri", name: "Lower Subansiri", state: "Arunachal Pradesh" },
      { id: "namsai", name: "Namsai", state: "Arunachal Pradesh" },
      { id: "pakke-kessang", name: "Pakke Kessang", state: "Arunachal Pradesh" },
      { id: "papum-pare", name: "Papum Pare", state: "Arunachal Pradesh" },
      { id: "shi-yomi", name: "Shi Yomi", state: "Arunachal Pradesh" },
      { id: "tawang", name: "Tawang", state: "Arunachal Pradesh" },
      { id: "tirap", name: "Tirap", state: "Arunachal Pradesh" },
      { id: "upper-siang", name: "Upper Siang", state: "Arunachal Pradesh" },
      { id: "upper-subansiri", name: "Upper Subansiri", state: "Arunachal Pradesh" },
      { id: "west-kameng", name: "West Kameng", state: "Arunachal Pradesh" },
      { id: "west-siang", name: "West Siang", state: "Arunachal Pradesh" }
    ]
  },
  {
    id: "assam",
    name: "Assam",
    districts: [
      { id: "baksa", name: "Baksa", state: "Assam" },
      { id: "barpeta", name: "Barpeta", state: "Assam" },
      { id: "biswanath", name: "Biswanath", state: "Assam" },
      { id: "bongaigaon", name: "Bongaigaon", state: "Assam" },
      { id: "cachar", name: "Cachar", state: "Assam" },
      { id: "charaideo", name: "Charaideo", state: "Assam" },
      { id: "chirang", name: "Chirang", state: "Assam" },
      { id: "darrang", name: "Darrang", state: "Assam" },
      { id: "dhemaji", name: "Dhemaji", state: "Assam" },
      { id: "dhubri", name: "Dhubri", state: "Assam" },
      { id: "dibrugarh", name: "Dibrugarh", state: "Assam" },
      { id: "goalpara", name: "Goalpara", state: "Assam" },
      { id: "golaghat", name: "Golaghat", state: "Assam" },
      { id: "hailakandi", name: "Hailakandi", state: "Assam" },
      { id: "hojai", name: "Hojai", state: "Assam" },
      { id: "jorhat", name: "Jorhat", state: "Assam" },
      { id: "kamrup", name: "Kamrup", state: "Assam" },
      { id: "kamrup-metro", name: "Kamrup Metro", state: "Assam" },
      { id: "karbi-anglong", name: "Karbi Anglong", state: "Assam" },
      { id: "karimganj", name: "Karimganj", state: "Assam" },
      { id: "kokrajhar", name: "Kokrajhar", state: "Assam" },
      { id: "lakhimpur", name: "Lakhimpur", state: "Assam" },
      { id: "majuli", name: "Majuli", state: "Assam" },
      { id: "morigaon", name: "Morigaon", state: "Assam" },
      { id: "nagaon", name: "Nagaon", state: "Assam" },
      { id: "nalbari", name: "Nalbari", state: "Assam" },
      { id: "dima-hasao", name: "Dima Hasao", state: "Assam" },
      { id: "sivasagar", name: "Sivasagar", state: "Assam" },
      { id: "sonitpur", name: "Sonitpur", state: "Assam" },
      { id: "south-salmara-mankachar", name: "South Salmara-Mankachar", state: "Assam" },
      { id: "tinsukia", name: "Tinsukia", state: "Assam" },
      { id: "udalguri", name: "Udalguri", state: "Assam" },
      { id: "west-karbi-anglong", name: "West Karbi Anglong", state: "Assam" }
    ]
  },
  {
    id: "bihar",
    name: "Bihar",
    districts: [
      { id: "araria", name: "Araria", state: "Bihar" },
      { id: "arwal", name: "Arwal", state: "Bihar" },
      { id: "aurangabad", name: "Aurangabad", state: "Bihar" },
      { id: "banka", name: "Banka", state: "Bihar" },
      { id: "begusarai", name: "Begusarai", state: "Bihar" },
      { id: "bhagalpur", name: "Bhagalpur", state: "Bihar" },
      { id: "bhojpur", name: "Bhojpur", state: "Bihar" },
      { id: "buxar", name: "Buxar", state: "Bihar" },
      { id: "darbhanga", name: "Darbhanga", state: "Bihar" },
      { id: "east-champaran", name: "East Champaran", state: "Bihar" },
      { id: "gaya", name: "Gaya", state: "Bihar" },
      { id: "gopalganj", name: "Gopalganj", state: "Bihar" },
      { id: "jamui", name: "Jamui", state: "Bihar" },
      { id: "jehanabad", name: "Jehanabad", state: "Bihar" },
      { id: "kaimur", name: "Kaimur", state: "Bihar" },
      { id: "katihar", name: "Katihar", state: "Bihar" },
      { id: "khagaria", name: "Khagaria", state: "Bihar" },
      { id: "kishanganj", name: "Kishanganj", state: "Bihar" },
      { id: "lakhisarai", name: "Lakhisarai", state: "Bihar" },
      { id: "madhepura", name: "Madhepura", state: "Bihar" },
      { id: "madhubani", name: "Madhubani", state: "Bihar" },
      { id: "munger", name: "Munger", state: "Bihar" },
      { id: "muzaffarpur", name: "Muzaffarpur", state: "Bihar" },
      { id: "nalanda", name: "Nalanda", state: "Bihar" },
      { id: "nawada", name: "Nawada", state: "Bihar" },
      { id: "patna", name: "Patna", state: "Bihar" },
      { id: "purnia", name: "Purnia", state: "Bihar" },
      { id: "rohtas", name: "Rohtas", state: "Bihar" },
      { id: "saharsa", name: "Saharsa", state: "Bihar" },
      { id: "samastipur", name: "Samastipur", state: "Bihar" },
      { id: "saran", name: "Saran", state: "Bihar" },
      { id: "sheikhpura", name: "Sheikhpura", state: "Bihar" },
      { id: "sheohar", name: "Sheohar", state: "Bihar" },
      { id: "sitamarhi", name: "Sitamarhi", state: "Bihar" },
      { id: "siwan", name: "Siwan", state: "Bihar" },
      { id: "supaul", name: "Supaul", state: "Bihar" },
      { id: "vaishali", name: "Vaishali", state: "Bihar" },
      { id: "west-champaran", name: "West Champaran", state: "Bihar" }
    ]
  },
  {
    id: "chhattisgarh",
    name: "Chhattisgarh",
    districts: [
      { id: "balod", name: "Balod", state: "Chhattisgarh" },
      { id: "baloda-bazar", name: "Baloda Bazar", state: "Chhattisgarh" },
      { id: "balrampur", name: "Balrampur", state: "Chhattisgarh" },
      { id: "bastar", name: "Bastar", state: "Chhattisgarh" },
      { id: "bemetara", name: "Bemetara", state: "Chhattisgarh" },
      { id: "bijapur", name: "Bijapur", state: "Chhattisgarh" },
      { id: "bilaspur", name: "Bilaspur", state: "Chhattisgarh" },
      { id: "dantewada", name: "Dantewada", state: "Chhattisgarh" },
      { id: "dhamtari", name: "Dhamtari", state: "Chhattisgarh" },
      { id: "durg", name: "Durg", state: "Chhattisgarh" },
      { id: "gariaband", name: "Gariaband", state: "Chhattisgarh" },
      { id: "janjgir-champa", name: "Janjgir-Champa", state: "Chhattisgarh" },
      { id: "jashpur", name: "Jashpur", state: "Chhattisgarh" },
      { id: "kabirdham", name: "Kabirdham", state: "Chhattisgarh" },
      { id: "kanker", name: "Kanker", state: "Chhattisgarh" },
      { id: "kondagaon", name: "Kondagaon", state: "Chhattisgarh" },
      { id: "korba", name: "Korba", state: "Chhattisgarh" },
      { id: "koriya", name: "Koriya", state: "Chhattisgarh" },
      { id: "mahasamund", name: "Mahasamund", state: "Chhattisgarh" },
      { id: "mungeli", name: "Mungeli", state: "Chhattisgarh" },
      { id: "narayanpur", name: "Narayanpur", state: "Chhattisgarh" },
      { id: "raigarh", name: "Raigarh", state: "Chhattisgarh" },
      { id: "raipur", name: "Raipur", state: "Chhattisgarh" },
      { id: "rajnandgaon", name: "Rajnandgaon", state: "Chhattisgarh" },
      { id: "sukma", name: "Sukma", state: "Chhattisgarh" },
      { id: "surajpur", name: "Surajpur", state: "Chhattisgarh" },
      { id: "surguja", name: "Surguja", state: "Chhattisgarh" }
    ]
  },
  {
    id: "goa",
    name: "Goa",
    districts: [
      { id: "north-goa", name: "North Goa", state: "Goa" },
      { id: "south-goa", name: "South Goa", state: "Goa" }
    ]
  },
  {
    id: "gujarat",
    name: "Gujarat",
    districts: [
      { id: "ahmedabad", name: "Ahmedabad", state: "Gujarat" },
      { id: "amreli", name: "Amreli", state: "Gujarat" },
      { id: "anand", name: "Anand", state: "Gujarat" },
      { id: "aravalli", name: "Aravalli", state: "Gujarat" },
      { id: "banaskantha", name: "Banaskantha", state: "Gujarat" },
      { id: "bharuch", name: "Bharuch", state: "Gujarat" },
      { id: "bhavnagar", name: "Bhavnagar", state: "Gujarat" },
      { id: "botad", name: "Botad", state: "Gujarat" },
      { id: "chhota-udaipur", name: "Chhota Udaipur", state: "Gujarat" },
      { id: "dahod", name: "Dahod", state: "Gujarat" },
      { id: "dang", name: "Dang", state: "Gujarat" },
      { id: "devbhoomi-dwarka", name: "Devbhoomi Dwarka", state: "Gujarat" },
      { id: "gandhinagar", name: "Gandhinagar", state: "Gujarat" },
      { id: "gir-somnath", name: "Gir Somnath", state: "Gujarat" },
      { id: "jamnagar", name: "Jamnagar", state: "Gujarat" },
      { id: "junagadh", name: "Junagadh", state: "Gujarat" },
      { id: "kachchh", name: "Kachchh", state: "Gujarat" },
      { id: "kheda", name: "Kheda", state: "Gujarat" },
      { id: "mahisagar", name: "Mahisagar", state: "Gujarat" },
      { id: "mehsana", name: "Mehsana", state: "Gujarat" },
      { id: "morbi", name: "Morbi", state: "Gujarat" },
      { id: "narmada", name: "Narmada", state: "Gujarat" },
      { id: "navsari", name: "Navsari", state: "Gujarat" },
      { id: "panchmahal", name: "Panchmahal", state: "Gujarat" },
      { id: "patan", name: "Patan", state: "Gujarat" },
      { id: "porbandar", name: "Porbandar", state: "Gujarat" },
      { id: "rajkot", name: "Rajkot", state: "Gujarat" },
      { id: "sabarkantha", name: "Sabarkantha", state: "Gujarat" },
      { id: "surat", name: "Surat", state: "Gujarat" },
      { id: "surendranagar", name: "Surendranagar", state: "Gujarat" },
      { id: "tapi", name: "Tapi", state: "Gujarat" },
      { id: "vadodara", name: "Vadodara", state: "Gujarat" },
      { id: "valsad", name: "Valsad", state: "Gujarat" }
    ]
  },
  {
    id: "haryana",
    name: "Haryana",
    districts: [
      { id: "ambala", name: "Ambala", state: "Haryana" },
      { id: "bhiwani", name: "Bhiwani", state: "Haryana" },
      { id: "charkhi-dadri", name: "Charkhi Dadri", state: "Haryana" },
      { id: "faridabad", name: "Faridabad", state: "Haryana" },
      { id: "fatehabad", name: "Fatehabad", state: "Haryana" },
      { id: "gurugram", name: "Gurugram", state: "Haryana" },
      { id: "hisar", name: "Hisar", state: "Haryana" },
      { id: "jhajjar", name: "Jhajjar", state: "Haryana" },
      { id: "jind", name: "Jind", state: "Haryana" },
      { id: "kaithal", name: "Kaithal", state: "Haryana" },
      { id: "karnal", name: "Karnal", state: "Haryana" },
      { id: "kurukshetra", name: "Kurukshetra", state: "Haryana" },
      { id: "mahendragarh", name: "Mahendragarh", state: "Haryana" },
      { id: "nuh", name: "Nuh", state: "Haryana" },
      { id: "palwal", name: "Palwal", state: "Haryana" },
      { id: "panchkula", name: "Panchkula", state: "Haryana" },
      { id: "panipat", name: "Panipat", state: "Haryana" },
      { id: "rewari", name: "Rewari", state: "Haryana" },
      { id: "rohtak", name: "Rohtak", state: "Haryana" },
      { id: "sirsa", name: "Sirsa", state: "Haryana" },
      { id: "sonipat", name: "Sonipat", state: "Haryana" },
      { id: "yamunanagar", name: "Yamunanagar", state: "Haryana" }
    ]
  },
  {
    id: "himachal-pradesh",
    name: "Himachal Pradesh",
    districts: [
      { id: "bilaspur-hp", name: "Bilaspur", state: "Himachal Pradesh" },
      { id: "chamba", name: "Chamba", state: "Himachal Pradesh" },
      { id: "hamirpur-hp", name: "Hamirpur", state: "Himachal Pradesh" },
      { id: "kangra", name: "Kangra", state: "Himachal Pradesh" },
      { id: "kinnaur", name: "Kinnaur", state: "Himachal Pradesh" },
      { id: "kullu", name: "Kullu", state: "Himachal Pradesh" },
      { id: "lahaul-spiti", name: "Lahaul and Spiti", state: "Himachal Pradesh" },
      { id: "mandi", name: "Mandi", state: "Himachal Pradesh" },
      { id: "shimla", name: "Shimla", state: "Himachal Pradesh" },
      { id: "sirmaur", name: "Sirmaur", state: "Himachal Pradesh" },
      { id: "solan", name: "Solan", state: "Himachal Pradesh" },
      { id: "una", name: "Una", state: "Himachal Pradesh" }
    ]
  },
  {
    id: "jharkhand",
    name: "Jharkhand",
    districts: [
      { id: "bokaro", name: "Bokaro", state: "Jharkhand" },
      { id: "chatra", name: "Chatra", state: "Jharkhand" },
      { id: "deoghar", name: "Deoghar", state: "Jharkhand" },
      { id: "dhanbad", name: "Dhanbad", state: "Jharkhand" },
      { id: "dumka", name: "Dumka", state: "Jharkhand" },
      { id: "east-singhbhum", name: "East Singhbhum", state: "Jharkhand" },
      { id: "garhwa", name: "Garhwa", state: "Jharkhand" },
      { id: "giridih", name: "Giridih", state: "Jharkhand" },
      { id: "godda", name: "Godda", state: "Jharkhand" },
      { id: "gumla", name: "Gumla", state: "Jharkhand" },
      { id: "hazaribagh", name: "Hazaribagh", state: "Jharkhand" },
      { id: "jamtara", name: "Jamtara", state: "Jharkhand" },
      { id: "khunti", name: "Khunti", state: "Jharkhand" },
      { id: "koderma", name: "Koderma", state: "Jharkhand" },
      { id: "latehar", name: "Latehar", state: "Jharkhand" },
      { id: "lohardaga", name: "Lohardaga", state: "Jharkhand" },
      { id: "pakur", name: "Pakur", state: "Jharkhand" },
      { id: "palamu", name: "Palamu", state: "Jharkhand" },
      { id: "ramgarh", name: "Ramgarh", state: "Jharkhand" },
      { id: "ranchi", name: "Ranchi", state: "Jharkhand" },
      { id: "sahibganj", name: "Sahibganj", state: "Jharkhand" },
      { id: "seraikela-kharsawan", name: "Seraikela Kharsawan", state: "Jharkhand" },
      { id: "simdega", name: "Simdega", state: "Jharkhand" },
      { id: "west-singhbhum", name: "West Singhbhum", state: "Jharkhand" }
    ]
  },
  {
    id: "karnataka",
    name: "Karnataka",
    districts: [
      { id: "bagalkot", name: "Bagalkot", state: "Karnataka" },
      { id: "ballari", name: "Ballari", state: "Karnataka" },
      { id: "belagavi", name: "Belagavi", state: "Karnataka" },
      { id: "bengaluru-rural", name: "Bengaluru Rural", state: "Karnataka" },
      { id: "bengaluru-urban", name: "Bengaluru Urban", state: "Karnataka" },
      { id: "bidar", name: "Bidar", state: "Karnataka" },
      { id: "chamarajanagar", name: "Chamarajanagar", state: "Karnataka" },
      { id: "chikkaballapur", name: "Chikkaballapur", state: "Karnataka" },
      { id: "chikkamagaluru", name: "Chikkamagaluru", state: "Karnataka" },
      { id: "chitradurga", name: "Chitradurga", state: "Karnataka" },
      { id: "dakshina-kannada", name: "Dakshina Kannada", state: "Karnataka" },
      { id: "davanagere", name: "Davanagere", state: "Karnataka" },
      { id: "dharwad", name: "Dharwad", state: "Karnataka" },
      { id: "gadag", name: "Gadag", state: "Karnataka" },
      { id: "hassan", name: "Hassan", state: "Karnataka" },
      { id: "haveri", name: "Haveri", state: "Karnataka" },
      { id: "kalaburagi", name: "Kalaburagi", state: "Karnataka" },
      { id: "kodagu", name: "Kodagu", state: "Karnataka" },
      { id: "kolar", name: "Kolar", state: "Karnataka" },
      { id: "koppal", name: "Koppal", state: "Karnataka" },
      { id: "mandya", name: "Mandya", state: "Karnataka" },
      { id: "mysuru", name: "Mysuru", state: "Karnataka" },
      { id: "raichur", name: "Raichur", state: "Karnataka" },
      { id: "ramanagara", name: "Ramanagara", state: "Karnataka" },
      { id: "shivamogga", name: "Shivamogga", state: "Karnataka" },
      { id: "tumakuru", name: "Tumakuru", state: "Karnataka" },
      { id: "udupi", name: "Udupi", state: "Karnataka" },
      { id: "uttara-kannada", name: "Uttara Kannada", state: "Karnataka" },
      { id: "vijayapura", name: "Vijayapura", state: "Karnataka" },
      { id: "yadgir", name: "Yadgir", state: "Karnataka" }
    ]
  },
  {
    id: "kerala",
    name: "Kerala",
    districts: [
      { id: "alappuzha", name: "Alappuzha", state: "Kerala" },
      { id: "ernakulam", name: "Ernakulam", state: "Kerala" },
      { id: "idukki", name: "Idukki", state: "Kerala" },
      { id: "kannur", name: "Kannur", state: "Kerala" },
      { id: "kasaragod", name: "Kasaragod", state: "Kerala" },
      { id: "kollam", name: "Kollam", state: "Kerala" },
      { id: "kottayam", name: "Kottayam", state: "Kerala" },
      { id: "kozhikode", name: "Kozhikode", state: "Kerala" },
      { id: "malappuram", name: "Malappuram", state: "Kerala" },
      { id: "palakkad", name: "Palakkad", state: "Kerala" },
      { id: "pathanamthitta", name: "Pathanamthitta", state: "Kerala" },
      { id: "thiruvananthapuram", name: "Thiruvananthapuram", state: "Kerala" },
      { id: "thrissur", name: "Thrissur", state: "Kerala" },
      { id: "wayanad", name: "Wayanad", state: "Kerala" }
    ]
  },
  {
    id: "madhya-pradesh",
    name: "Madhya Pradesh",
    districts: [
      { id: "agar-malwa", name: "Agar Malwa", state: "Madhya Pradesh" },
      { id: "alirajpur", name: "Alirajpur", state: "Madhya Pradesh" },
      { id: "anuppur", name: "Anuppur", state: "Madhya Pradesh" },
      { id: "ashoknagar", name: "Ashoknagar", state: "Madhya Pradesh" },
      { id: "balaghat", name: "Balaghat", state: "Madhya Pradesh" },
      { id: "barwani", name: "Barwani", state: "Madhya Pradesh" },
      { id: "betul", name: "Betul", state: "Madhya Pradesh" },
      { id: "bhind", name: "Bhind", state: "Madhya Pradesh" },
      { id: "bhopal", name: "Bhopal", state: "Madhya Pradesh" },
      { id: "burhanpur", name: "Burhanpur", state: "Madhya Pradesh" },
      { id: "chhatarpur", name: "Chhatarpur", state: "Madhya Pradesh" },
      { id: "chhindwara", name: "Chhindwara", state: "Madhya Pradesh" },
      { id: "damoh", name: "Damoh", state: "Madhya Pradesh" },
      { id: "datia", name: "Datia", state: "Madhya Pradesh" },
      { id: "dewas", name: "Dewas", state: "Madhya Pradesh" },
      { id: "dhar", name: "Dhar", state: "Madhya Pradesh" },
      { id: "dindori", name: "Dindori", state: "Madhya Pradesh" },
      { id: "guna", name: "Guna", state: "Madhya Pradesh" },
      { id: "gwalior", name: "Gwalior", state: "Madhya Pradesh" },
      { id: "harda", name: "Harda", state: "Madhya Pradesh" },
      { id: "hoshangabad", name: "Hoshangabad", state: "Madhya Pradesh" },
      { id: "indore", name: "Indore", state: "Madhya Pradesh" },
      { id: "jabalpur", name: "Jabalpur", state: "Madhya Pradesh" },
      { id: "jhabua", name: "Jhabua", state: "Madhya Pradesh" },
      { id: "katni", name: "Katni", state: "Madhya Pradesh" },
      { id: "khandwa", name: "Khandwa", state: "Madhya Pradesh" },
      { id: "khargone", name: "Khargone", state: "Madhya Pradesh" },
      { id: "mandla", name: "Mandla", state: "Madhya Pradesh" },
      { id: "mandsaur", name: "Mandsaur", state: "Madhya Pradesh" },
      { id: "morena", name: "Morena", state: "Madhya Pradesh" },
      { id: "narsinghpur", name: "Narsinghpur", state: "Madhya Pradesh" },
      { id: "neemuch", name: "Neemuch", state: "Madhya Pradesh" },
      { id: "niwari", name: "Niwari", state: "Madhya Pradesh" },
      { id: "panna", name: "Panna", state: "Madhya Pradesh" },
      { id: "raisen", name: "Raisen", state: "Madhya Pradesh" },
      { id: "rajgarh", name: "Rajgarh", state: "Madhya Pradesh" },
      { id: "ratlam", name: "Ratlam", state: "Madhya Pradesh" },
      { id: "rewa", name: "Rewa", state: "Madhya Pradesh" },
      { id: "sagar", name: "Sagar", state: "Madhya Pradesh" },
      { id: "satna", name: "Satna", state: "Madhya Pradesh" },
      { id: "sehore", name: "Sehore", state: "Madhya Pradesh" },
      { id: "seoni", name: "Seoni", state: "Madhya Pradesh" },
      { id: "shahdol", name: "Shahdol", state: "Madhya Pradesh" },
      { id: "shajapur", name: "Shajapur", state: "Madhya Pradesh" },
      { id: "sheopur", name: "Sheopur", state: "Madhya Pradesh" },
      { id: "shivpuri", name: "Shivpuri", state: "Madhya Pradesh" },
      { id: "sidhi", name: "Sidhi", state: "Madhya Pradesh" },
      { id: "singrauli", name: "Singrauli", state: "Madhya Pradesh" },
      { id: "tikamgarh", name: "Tikamgarh", state: "Madhya Pradesh" },
      { id: "ujjain", name: "Ujjain", state: "Madhya Pradesh" },
      { id: "umaria", name: "Umaria", state: "Madhya Pradesh" },
      { id: "vidisha", name: "Vidisha", state: "Madhya Pradesh" }
    ]
  },
  {
    id: "maharashtra",
    name: "Maharashtra",
    districts: [
      { id: "ahmednagar", name: "Ahmednagar", state: "Maharashtra" },
      { id: "akola", name: "Akola", state: "Maharashtra" },
      { id: "amravati", name: "Amravati", state: "Maharashtra" },
      { id: "aurangabad-mh", name: "Aurangabad", state: "Maharashtra" },
      { id: "beed", name: "Beed", state: "Maharashtra" },
      { id: "bhandara", name: "Bhandara", state: "Maharashtra" },
      { id: "buldhana", name: "Buldhana", state: "Maharashtra" },
      { id: "chandrapur", name: "Chandrapur", state: "Maharashtra" },
      { id: "dhule", name: "Dhule", state: "Maharashtra" },
      { id: "gadchiroli", name: "Gadchiroli", state: "Maharashtra" },
      { id: "gondia", name: "Gondia", state: "Maharashtra" },
      { id: "hingoli", name: "Hingoli", state: "Maharashtra" },
      { id: "jalgaon", name: "Jalgaon", state: "Maharashtra" },
      { id: "jalna", name: "Jalna", state: "Maharashtra" },
      { id: "kolhapur", name: "Kolhapur", state: "Maharashtra" },
      { id: "latur", name: "Latur", state: "Maharashtra" },
      { id: "mumbai-city", name: "Mumbai City", state: "Maharashtra" },
      { id: "mumbai-suburban", name: "Mumbai Suburban", state: "Maharashtra" },
      { id: "nagpur", name: "Nagpur", state: "Maharashtra" },
      { id: "nanded", name: "Nanded", state: "Maharashtra" },
      { id: "nandurbar", name: "Nandurbar", state: "Maharashtra" },
      { id: "nashik", name: "Nashik", state: "Maharashtra" },
      { id: "osmanabad", name: "Osmanabad", state: "Maharashtra" },
      { id: "palghar", name: "Palghar", state: "Maharashtra" },
      { id: "parbhani", name: "Parbhani", state: "Maharashtra" },
      { id: "pune", name: "Pune", state: "Maharashtra" },
      { id: "raigad", name: "Raigad", state: "Maharashtra" },
      { id: "ratnagiri", name: "Ratnagiri", state: "Maharashtra" },
      { id: "sangli", name: "Sangli", state: "Maharashtra" },
      { id: "satara", name: "Satara", state: "Maharashtra" },
      { id: "sindhudurg", name: "Sindhudurg", state: "Maharashtra" },
      { id: "solapur", name: "Solapur", state: "Maharashtra" },
      { id: "thane", name: "Thane", state: "Maharashtra" },
      { id: "wardha", name: "Wardha", state: "Maharashtra" },
      { id: "washim", name: "Washim", state: "Maharashtra" },
      { id: "yavatmal", name: "Yavatmal", state: "Maharashtra" }
    ]
  },
  {
    id: "manipur",
    name: "Manipur",
    districts: [
      { id: "bishnupur", name: "Bishnupur", state: "Manipur" },
      { id: "chandel", name: "Chandel", state: "Manipur" },
      { id: "churachandpur", name: "Churachandpur", state: "Manipur" },
      { id: "imphal-east", name: "Imphal East", state: "Manipur" },
      { id: "imphal-west", name: "Imphal West", state: "Manipur" },
      { id: "jiribam", name: "Jiribam", state: "Manipur" },
      { id: "kakching", name: "Kakching", state: "Manipur" },
      { id: "kamjong", name: "Kamjong", state: "Manipur" },
      { id: "kangpokpi", name: "Kangpokpi", state: "Manipur" },
      { id: "noney", name: "Noney", state: "Manipur" },
      { id: "pherzawl", name: "Pherzawl", state: "Manipur" },
      { id: "senapati", name: "Senapati", state: "Manipur" },
      { id: "tamenglong", name: "Tamenglong", state: "Manipur" },
      { id: "tengnoupal", name: "Tengnoupal", state: "Manipur" },
      { id: "thoubal", name: "Thoubal", state: "Manipur" },
      { id: "ukhrul", name: "Ukhrul", state: "Manipur" }
    ]
  },
  {
    id: "meghalaya",
    name: "Meghalaya",
    districts: [
      { id: "east-garo-hills", name: "East Garo Hills", state: "Meghalaya" },
      { id: "east-jaintia-hills", name: "East Jaintia Hills", state: "Meghalaya" },
      { id: "east-khasi-hills", name: "East Khasi Hills", state: "Meghalaya" },
      { id: "north-garo-hills", name: "North Garo Hills", state: "Meghalaya" },
      { id: "ribhoi", name: "Ribhoi", state: "Meghalaya" },
      { id: "south-garo-hills", name: "South Garo Hills", state: "Meghalaya" },
      { id: "south-west-garo-hills", name: "South West Garo Hills", state: "Meghalaya" },
      { id: "south-west-khasi-hills", name: "South West Khasi Hills", state: "Meghalaya" },
      { id: "west-garo-hills", name: "West Garo Hills", state: "Meghalaya" },
      { id: "west-jaintia-hills", name: "West Jaintia Hills", state: "Meghalaya" },
      { id: "west-khasi-hills", name: "West Khasi Hills", state: "Meghalaya" }
    ]
  },
  {
    id: "mizoram",
    name: "Mizoram",
    districts: [
      { id: "aizawl", name: "Aizawl", state: "Mizoram" },
      { id: "champhai", name: "Champhai", state: "Mizoram" },
      { id: "hnahthial", name: "Hnahthial", state: "Mizoram" },
      { id: "kolasib", name: "Kolasib", state: "Mizoram" },
      { id: "khawzawl", name: "Khawzawl", state: "Mizoram" },
      { id: "lawngtlai", name: "Lawngtlai", state: "Mizoram" },
      { id: "lunglei", name: "Lunglei", state: "Mizoram" },
      { id: "mamit", name: "Mamit", state: "Mizoram" },
      { id: "saiha", name: "Saiha", state: "Mizoram" },
      { id: "saitual", name: "Saitual", state: "Mizoram" },
      { id: "serchhip", name: "Serchhip", state: "Mizoram" }
    ]
  },
  {
    id: "nagaland",
    name: "Nagaland",
    districts: [
      { id: "dimapur", name: "Dimapur", state: "Nagaland" },
      { id: "kiphire", name: "Kiphire", state: "Nagaland" },
      { id: "kohima", name: "Kohima", state: "Nagaland" },
      { id: "longleng", name: "Longleng", state: "Nagaland" },
      { id: "mokokchung", name: "Mokokchung", state: "Nagaland" },
      { id: "mon", name: "Mon", state: "Nagaland" },
      { id: "noklak", name: "Noklak", state: "Nagaland" },
      { id: "peren", name: "Peren", state: "Nagaland" },
      { id: "phek", name: "Phek", state: "Nagaland" },
      { id: "tuensang", name: "Tuensang", state: "Nagaland" },
      { id: "wokha", name: "Wokha", state: "Nagaland" },
      { id: "zunheboto", name: "Zunheboto", state: "Nagaland" }
    ]
  },
  {
    id: "odisha",
    name: "Odisha",
    districts: [
      { id: "angul", name: "Angul", state: "Odisha" },
      { id: "balangir", name: "Balangir", state: "Odisha" },
      { id: "balasore", name: "Balasore", state: "Odisha" },
      { id: "bargarh", name: "Bargarh", state: "Odisha" },
      { id: "bhadrak", name: "Bhadrak", state: "Odisha" },
      { id: "boudh", name: "Boudh", state: "Odisha" },
      { id: "cuttack", name: "Cuttack", state: "Odisha" },
      { id: "deogarh", name: "Deogarh", state: "Odisha" },
      { id: "dhenkanal", name: "Dhenkanal", state: "Odisha" },
      { id: "gajapati", name: "Gajapati", state: "Odisha" },
      { id: "ganjam", name: "Ganjam", state: "Odisha" },
      { id: "jagatsinghpur", name: "Jagatsinghpur", state: "Odisha" },
      { id: "jajpur", name: "Jajpur", state: "Odisha" },
      { id: "jharsuguda", name: "Jharsuguda", state: "Odisha" },
      { id: "kalahandi", name: "Kalahandi", state: "Odisha" },
      { id: "kandhamal", name: "Kandhamal", state: "Odisha" },
      { id: "kendrapara", name: "Kendrapara", state: "Odisha" },
      { id: "kendujhar", name: "Kendujhar", state: "Odisha" },
      { id: "khordha", name: "Khordha", state: "Odisha" },
      { id: "koraput", name: "Koraput", state: "Odisha" },
      { id: "malkangiri", name: "Malkangiri", state: "Odisha" },
      { id: "mayurbhanj", name: "Mayurbhanj", state: "Odisha" },
      { id: "nabarangpur", name: "Nabarangpur", state: "Odisha" },
      { id: "nayagarh", name: "Nayagarh", state: "Odisha" },
      { id: "nuapada", name: "Nuapada", state: "Odisha" },
      { id: "puri", name: "Puri", state: "Odisha" },
      { id: "rayagada", name: "Rayagada", state: "Odisha" },
      { id: "sambalpur", name: "Sambalpur", state: "Odisha" },
      { id: "subarnapur", name: "Subarnapur", state: "Odisha" },
      { id: "sundargarh", name: "Sundargarh", state: "Odisha" }
    ]
  },
  {
    id: "punjab",
    name: "Punjab",
    districts: [
      { id: "amritsar", name: "Amritsar", state: "Punjab" },
      { id: "barnala", name: "Barnala", state: "Punjab" },
      { id: "bathinda", name: "Bathinda", state: "Punjab" },
      { id: "faridkot", name: "Faridkot", state: "Punjab" },
      { id: "fatehgarh-sahib", name: "Fatehgarh Sahib", state: "Punjab" },
      { id: "fazilka", name: "Fazilka", state: "Punjab" },
      { id: "ferozepur", name: "Ferozepur", state: "Punjab" },
      { id: "gurdaspur", name: "Gurdaspur", state: "Punjab" },
      { id: "hoshiarpur", name: "Hoshiarpur", state: "Punjab" },
      { id: "jalandhar", name: "Jalandhar", state: "Punjab" },
      { id: "kapurthala", name: "Kapurthala", state: "Punjab" },
      { id: "ludhiana", name: "Ludhiana", state: "Punjab" },
      { id: "mansa", name: "Mansa", state: "Punjab" },
      { id: "moga", name: "Moga", state: "Punjab" },
      { id: "pathankot", name: "Pathankot", state: "Punjab" },
      { id: "patiala", name: "Patiala", state: "Punjab" },
      { id: "rupnagar", name: "Rupnagar", state: "Punjab" },
      { id: "sahibzada-ajit-singh-nagar", name: "Sahibzada Ajit Singh Nagar", state: "Punjab" },
      { id: "sangrur", name: "Sangrur", state: "Punjab" },
      { id: "shaheed-bhagat-singh-nagar", name: "Shaheed Bhagat Singh Nagar", state: "Punjab" },
      { id: "sri-muktsar-sahib", name: "Sri Muktsar Sahib", state: "Punjab" },
      { id: "tarn-taran", name: "Tarn Taran", state: "Punjab" }
    ]
  },
  {
    id: "rajasthan",
    name: "Rajasthan",
    districts: [
      { id: "ajmer", name: "Ajmer", state: "Rajasthan" },
      { id: "alwar", name: "Alwar", state: "Rajasthan" },
      { id: "banswara", name: "Banswara", state: "Rajasthan" },
      { id: "baran", name: "Baran", state: "Rajasthan" },
      { id: "barmer", name: "Barmer", state: "Rajasthan" },
      { id: "bharatpur", name: "Bharatpur", state: "Rajasthan" },
      { id: "bhilwara", name: "Bhilwara", state: "Rajasthan" },
      { id: "bikaner", name: "Bikaner", state: "Rajasthan" },
      { id: "bundi", name: "Bundi", state: "Rajasthan" },
      { id: "chittorgarh", name: "Chittorgarh", state: "Rajasthan" },
      { id: "churu", name: "Churu", state: "Rajasthan" },
      { id: "dausa", name: "Dausa", state: "Rajasthan" },
      { id: "dholpur", name: "Dholpur", state: "Rajasthan" },
      { id: "dungarpur", name: "Dungarpur", state: "Rajasthan" },
      { id: "hanumangarh", name: "Hanumangarh", state: "Rajasthan" },
      { id: "jaipur", name: "Jaipur", state: "Rajasthan" },
      { id: "jaisalmer", name: "Jaisalmer", state: "Rajasthan" },
      { id: "jalore", name: "Jalore", state: "Rajasthan" },
      { id: "jhalawar", name: "Jhalawar", state: "Rajasthan" },
      { id: "jhunjhunu", name: "Jhunjhunu", state: "Rajasthan" },
      { id: "jodhpur", name: "Jodhpur", state: "Rajasthan" },
      { id: "karauli", name: "Karauli", state: "Rajasthan" },
      { id: "kota", name: "Kota", state: "Rajasthan" },
      { id: "nagaur", name: "Nagaur", state: "Rajasthan" },
      { id: "pali", name: "Pali", state: "Rajasthan" },
      { id: "pratapgarh", name: "Pratapgarh", state: "Rajasthan" },
      { id: "rajsamand", name: "Rajsamand", state: "Rajasthan" },
      { id: "sawai-madhopur", name: "Sawai Madhopur", state: "Rajasthan" },
      { id: "sikar", name: "Sikar", state: "Rajasthan" },
      { id: "sirohi", name: "Sirohi", state: "Rajasthan" },
      { id: "sri-ganganagar", name: "Sri Ganganagar", state: "Rajasthan" },
      { id: "tonk", name: "Tonk", state: "Rajasthan" },
      { id: "udaipur", name: "Udaipur", state: "Rajasthan" }
    ]
  },
  {
    id: "sikkim",
    name: "Sikkim",
    districts: [
      { id: "east-sikkim", name: "East Sikkim", state: "Sikkim" },
      { id: "north-sikkim", name: "North Sikkim", state: "Sikkim" },
      { id: "south-sikkim", name: "South Sikkim", state: "Sikkim" },
      { id: "west-sikkim", name: "West Sikkim", state: "Sikkim" }
    ]
  },
  {
    id: "tamil-nadu",
    name: "Tamil Nadu",
    districts: [
      { id: "ariyalur", name: "Ariyalur", state: "Tamil Nadu" },
      { id: "chengalpattu", name: "Chengalpattu", state: "Tamil Nadu" },
      { id: "chennai", name: "Chennai", state: "Tamil Nadu" },
      { id: "coimbatore", name: "Coimbatore", state: "Tamil Nadu" },
      { id: "cuddalore", name: "Cuddalore", state: "Tamil Nadu" },
      { id: "dharmapuri", name: "Dharmapuri", state: "Tamil Nadu" },
      { id: "dindigul", name: "Dindigul", state: "Tamil Nadu" },
      { id: "erode", name: "Erode", state: "Tamil Nadu" },
      { id: "kallakurichi", name: "Kallakurichi", state: "Tamil Nadu" },
      { id: "kanchipuram", name: "Kanchipuram", state: "Tamil Nadu" },
      { id: "kanyakumari", name: "Kanyakumari", state: "Tamil Nadu" },
      { id: "karur", name: "Karur", state: "Tamil Nadu" },
      { id: "krishnagiri", name: "Krishnagiri", state: "Tamil Nadu" },
      { id: "madurai", name: "Madurai", state: "Tamil Nadu" },
      { id: "mayiladuthurai", name: "Mayiladuthurai", state: "Tamil Nadu" },
      { id: "nagapattinam", name: "Nagapattinam", state: "Tamil Nadu" },
      { id: "namakkal", name: "Namakkal", state: "Tamil Nadu" },
      { id: "nilgiris", name: "Nilgiris", state: "Tamil Nadu" },
      { id: "perambalur", name: "Perambalur", state: "Tamil Nadu" },
      { id: "pudukkottai", name: "Pudukkottai", state: "Tamil Nadu" },
      { id: "ramanathapuram", name: "Ramanathapuram", state: "Tamil Nadu" },
      { id: "ranipet", name: "Ranipet", state: "Tamil Nadu" },
      { id: "salem", name: "Salem", state: "Tamil Nadu" },
      { id: "sivaganga", name: "Sivaganga", state: "Tamil Nadu" },
      { id: "tenkasi", name: "Tenkasi", state: "Tamil Nadu" },
      { id: "thanjavur", name: "Thanjavur", state: "Tamil Nadu" },
      { id: "theni", name: "Theni", state: "Tamil Nadu" },
      { id: "thoothukudi", name: "Thoothukudi", state: "Tamil Nadu" },
      { id: "tiruchirappalli", name: "Tiruchirappalli", state: "Tamil Nadu" },
      { id: "tirunelveli", name: "Tirunelveli", state: "Tamil Nadu" },
      { id: "tirupattur", name: "Tirupattur", state: "Tamil Nadu" },
      { id: "tiruppur", name: "Tiruppur", state: "Tamil Nadu" },
      { id: "tiruvallur", name: "Tiruvallur", state: "Tamil Nadu" },
      { id: "tiruvannamalai", name: "Tiruvannamalai", state: "Tamil Nadu" },
      { id: "tiruvarur", name: "Tiruvarur", state: "Tamil Nadu" },
      { id: "vellore", name: "Vellore", state: "Tamil Nadu" },
      { id: "viluppuram", name: "Viluppuram", state: "Tamil Nadu" },
      { id: "virudhunagar", name: "Virudhunagar", state: "Tamil Nadu" }
    ]
  },
  {
    id: "telangana",
    name: "Telangana",
    districts: [
      { id: "adilabad", name: "Adilabad", state: "Telangana" },
      { id: "bhadradri-kothagudem", name: "Bhadradri Kothagudem", state: "Telangana" },
      { id: "hyderabad", name: "Hyderabad", state: "Telangana" },
      { id: "jagtial", name: "Jagtial", state: "Telangana" },
      { id: "jangaon", name: "Jangaon", state: "Telangana" },
      { id: "jayashankar", name: "Jayashankar", state: "Telangana" },
      { id: "jogulamba", name: "Jogulamba", state: "Telangana" },
      { id: "kamareddy", name: "Kamareddy", state: "Telangana" },
      { id: "karimnagar", name: "Karimnagar", state: "Telangana" },
      { id: "khammam", name: "Khammam", state: "Telangana" },
      { id: "komaram-bheem", name: "Komaram Bheem", state: "Telangana" },
      { id: "mahabubabad", name: "Mahabubabad", state: "Telangana" },
      { id: "mahabubnagar", name: "Mahabubnagar", state: "Telangana" },
      { id: "mancherial", name: "Mancherial", state: "Telangana" },
      { id: "medak", name: "Medak", state: "Telangana" },
      { id: "medchal", name: "Medchal", state: "Telangana" },
      { id: "mulugu", name: "Mulugu", state: "Telangana" },
      { id: "nagarkurnool", name: "Nagarkurnool", state: "Telangana" },
      { id: "nalgonda", name: "Nalgonda", state: "Telangana" },
      { id: "narayanpet", name: "Narayanpet", state: "Telangana" },
      { id: "nirmal", name: "Nirmal", state: "Telangana" },
      { id: "nizamabad", name: "Nizamabad", state: "Telangana" },
      { id: "peddapalli", name: "Peddapalli", state: "Telangana" },
      { id: "rajanna-sircilla", name: "Rajanna Sircilla", state: "Telangana" },
      { id: "rangareddy", name: "Rangareddy", state: "Telangana" },
      { id: "sangareddy", name: "Sangareddy", state: "Telangana" },
      { id: "siddipet", name: "Siddipet", state: "Telangana" },
      { id: "suryapet", name: "Suryapet", state: "Telangana" },
      { id: "vikarabad", name: "Vikarabad", state: "Telangana" },
      { id: "wanaparthy", name: "Wanaparthy", state: "Telangana" },
      { id: "warangal-rural", name: "Warangal Rural", state: "Telangana" },
      { id: "warangal-urban", name: "Warangal Urban", state: "Telangana" },
      { id: "yadadri", name: "Yadadri", state: "Telangana" }
    ]
  },
  {
    id: "tripura",
    name: "Tripura",
    districts: [
      { id: "dhalai", name: "Dhalai", state: "Tripura" },
      { id: "gomati", name: "Gomati", state: "Tripura" },
      { id: "khowai", name: "Khowai", state: "Tripura" },
      { id: "north-tripura", name: "North Tripura", state: "Tripura" },
      { id: "sepahijala", name: "Sepahijala", state: "Tripura" },
      { id: "south-tripura", name: "South Tripura", state: "Tripura" },
      { id: "unakoti", name: "Unakoti", state: "Tripura" },
      { id: "west-tripura", name: "West Tripura", state: "Tripura" }
    ]
  },
  {
    id: "uttar-pradesh",
    name: "Uttar Pradesh",
    districts: [
      { id: "agra", name: "Agra", state: "Uttar Pradesh" },
      { id: "aligarh", name: "Aligarh", state: "Uttar Pradesh" },
      { id: "ambedkar-nagar", name: "Ambedkar Nagar", state: "Uttar Pradesh" },
      { id: "amethi", name: "Amethi", state: "Uttar Pradesh" },
      { id: "amroha", name: "Amroha", state: "Uttar Pradesh" },
      { id: "auraiya", name: "Auraiya", state: "Uttar Pradesh" },
      { id: "ayodhya", name: "Ayodhya", state: "Uttar Pradesh" },
      { id: "azamgarh", name: "Azamgarh", state: "Uttar Pradesh" },
      { id: "baghpat", name: "Baghpat", state: "Uttar Pradesh" },
      { id: "bahraich", name: "Bahraich", state: "Uttar Pradesh" },
      { id: "ballia", name: "Ballia", state: "Uttar Pradesh" },
      { id: "balrampur-up", name: "Balrampur", state: "Uttar Pradesh" },
      { id: "banda", name: "Banda", state: "Uttar Pradesh" },
      { id: "barabanki", name: "Barabanki", state: "Uttar Pradesh" },
      { id: "bareilly", name: "Bareilly", state: "Uttar Pradesh" },
      { id: "basti", name: "Basti", state: "Uttar Pradesh" },
      { id: "bhadohi", name: "Bhadohi", state: "Uttar Pradesh" },
      { id: "bijnor", name: "Bijnor", state: "Uttar Pradesh" },
      { id: "budaun", name: "Budaun", state: "Uttar Pradesh" },
      { id: "bulandshahr", name: "Bulandshahr", state: "Uttar Pradesh" },
      { id: "chandauli", name: "Chandauli", state: "Uttar Pradesh" },
      { id: "chitrakoot", name: "Chitrakoot", state: "Uttar Pradesh" },
      { id: "deoria", name: "Deoria", state: "Uttar Pradesh" },
      { id: "etah", name: "Etah", state: "Uttar Pradesh" },
      { id: "etawah", name: "Etawah", state: "Uttar Pradesh" },
      { id: "farrukhabad", name: "Farrukhabad", state: "Uttar Pradesh" },
      { id: "fatehpur", name: "Fatehpur", state: "Uttar Pradesh" },
      { id: "firozabad", name: "Firozabad", state: "Uttar Pradesh" },
      { id: "gautam-buddha-nagar", name: "Gautam Buddha Nagar", state: "Uttar Pradesh" },
      { id: "ghaziabad", name: "Ghaziabad", state: "Uttar Pradesh" },
      { id: "ghazipur", name: "Ghazipur", state: "Uttar Pradesh" },
      { id: "gonda", name: "Gonda", state: "Uttar Pradesh" },
      { id: "gorakhpur", name: "Gorakhpur", state: "Uttar Pradesh" },
      { id: "hamirpur-up", name: "Hamirpur", state: "Uttar Pradesh" },
      { id: "hapur", name: "Hapur", state: "Uttar Pradesh" },
      { id: "hardoi", name: "Hardoi", state: "Uttar Pradesh" },
      { id: "hathras", name: "Hathras", state: "Uttar Pradesh" },
      { id: "jalaun", name: "Jalaun", state: "Uttar Pradesh" },
      { id: "jaunpur", name: "Jaunpur", state: "Uttar Pradesh" },
      { id: "jhansi", name: "Jhansi", state: "Uttar Pradesh" },
      { id: "kannauj", name: "Kannauj", state: "Uttar Pradesh" },
      { id: "kanpur-dehat", name: "Kanpur Dehat", state: "Uttar Pradesh" },
      { id: "kanpur-nagar", name: "Kanpur Nagar", state: "Uttar Pradesh" },
      { id: "kasganj", name: "Kasganj", state: "Uttar Pradesh" },
      { id: "kaushambi", name: "Kaushambi", state: "Uttar Pradesh" },
      { id: "kheri", name: "Kheri", state: "Uttar Pradesh" },
      { id: "kushinagar", name: "Kushinagar", state: "Uttar Pradesh" },
      { id: "lalitpur", name: "Lalitpur", state: "Uttar Pradesh" },
      { id: "lucknow", name: "Lucknow", state: "Uttar Pradesh" },
      { id: "maharajganj", name: "Maharajganj", state: "Uttar Pradesh" },
      { id: "mahoba", name: "Mahoba", state: "Uttar Pradesh" },
      { id: "mainpuri", name: "Mainpuri", state: "Uttar Pradesh" },
      { id: "mathura", name: "Mathura", state: "Uttar Pradesh" },
      { id: "mau", name: "Mau", state: "Uttar Pradesh" },
      { id: "meerut", name: "Meerut", state: "Uttar Pradesh" },
      { id: "mirzapur", name: "Mirzapur", state: "Uttar Pradesh" },
      { id: "moradabad", name: "Moradabad", state: "Uttar Pradesh" },
      { id: "muzaffarnagar", name: "Muzaffarnagar", state: "Uttar Pradesh" },
      { id: "pilibhit", name: "Pilibhit", state: "Uttar Pradesh" },
      { id: "pratapgarh-up", name: "Pratapgarh", state: "Uttar Pradesh" },
      { id: "prayagraj", name: "Prayagraj", state: "Uttar Pradesh" },
      { id: "raebareli", name: "Raebareli", state: "Uttar Pradesh" },
      { id: "rampur", name: "Rampur", state: "Uttar Pradesh" },
      { id: "saharanpur", name: "Saharanpur", state: "Uttar Pradesh" },
      { id: "sambhal", name: "Sambhal", state: "Uttar Pradesh" },
      { id: "sant-kabir-nagar", name: "Sant Kabir Nagar", state: "Uttar Pradesh" },
      { id: "shahjahanpur", name: "Shahjahanpur", state: "Uttar Pradesh" },
      { id: "shamli", name: "Shamli", state: "Uttar Pradesh" },
      { id: "shrawasti", name: "Shrawasti", state: "Uttar Pradesh" },
      { id: "siddharthnagar", name: "Siddharthnagar", state: "Uttar Pradesh" },
      { id: "sitapur", name: "Sitapur", state: "Uttar Pradesh" },
      { id: "sonbhadra", name: "Sonbhadra", state: "Uttar Pradesh" },
      { id: "sultanpur", name: "Sultanpur", state: "Uttar Pradesh" },
      { id: "unnao", name: "Unnao", state: "Uttar Pradesh" },
      { id: "varanasi", name: "Varanasi", state: "Uttar Pradesh" }
    ]
  },
  {
    id: "uttarakhand",
    name: "Uttarakhand",
    districts: [
      { id: "almora", name: "Almora", state: "Uttarakhand" },
      { id: "bageshwar", name: "Bageshwar", state: "Uttarakhand" },
      { id: "chamoli", name: "Chamoli", state: "Uttarakhand" },
      { id: "champawat", name: "Champawat", state: "Uttarakhand" },
      { id: "dehradun", name: "Dehradun", state: "Uttarakhand" },
      { id: "haridwar", name: "Haridwar", state: "Uttarakhand" },
      { id: "nainital", name: "Nainital", state: "Uttarakhand" },
      { id: "pauri", name: "Pauri", state: "Uttarakhand" },
      { id: "pithoragarh", name: "Pithoragarh", state: "Uttarakhand" },
      { id: "rudraprayag", name: "Rudraprayag", state: "Uttarakhand" },
      { id: "tehri", name: "Tehri", state: "Uttarakhand" },
      { id: "udham-singh-nagar", name: "Udham Singh Nagar", state: "Uttarakhand" },
      { id: "uttarkashi", name: "Uttarkashi", state: "Uttarakhand" }
    ]
  },
  {
    id: "west-bengal",
    name: "West Bengal",
    districts: [
      { id: "alipurduar", name: "Alipurduar", state: "West Bengal" },
      { id: "bankura", name: "Bankura", state: "West Bengal" },
      { id: "birbhum", name: "Birbhum", state: "West Bengal" },
      { id: "cooch-behar", name: "Cooch Behar", state: "West Bengal" },
      { id: "dakshin-dinajpur", name: "Dakshin Dinajpur", state: "West Bengal" },
      { id: "darjeeling", name: "Darjeeling", state: "West Bengal" },
      { id: "hooghly", name: "Hooghly", state: "West Bengal" },
      { id: "howrah", name: "Howrah", state: "West Bengal" },
      { id: "jalpaiguri", name: "Jalpaiguri", state: "West Bengal" },
      { id: "jhargram", name: "Jhargram", state: "West Bengal" },
      { id: "kalimpong", name: "Kalimpong", state: "West Bengal" },
      { id: "kolkata", name: "Kolkata", state: "West Bengal" },
      { id: "malda", name: "Malda", state: "West Bengal" },
      { id: "murshidabad", name: "Murshidabad", state: "West Bengal" },
      { id: "nadia", name: "Nadia", state: "West Bengal" },
      { id: "north-24-parganas", name: "North 24 Parganas", state: "West Bengal" },
      { id: "paschim-bardhaman", name: "Paschim Bardhaman", state: "West Bengal" },
      { id: "paschim-medinipur", name: "Paschim Medinipur", state: "West Bengal" },
      { id: "purba-bardhaman", name: "Purba Bardhaman", state: "West Bengal" },
      { id: "purba-medinipur", name: "Purba Medinipur", state: "West Bengal" },
      { id: "purulia", name: "Purulia", state: "West Bengal" },
      { id: "south-24-parganas", name: "South 24 Parganas", state: "West Bengal" },
      { id: "uttar-dinajpur", name: "Uttar Dinajpur", state: "West Bengal" }
    ]
  }
];

// Function to get all states
export const getAllStates = (): string[] => {
  return INDIAN_STATES_DISTRICTS.map(state => state.name);
};

// Function to get districts for a specific state
export const getDistrictsByState = (stateName: string): District[] => {
  const state = INDIAN_STATES_DISTRICTS.find(s => s.name === stateName);
  return state ? state.districts : [];
};

// Function to get all districts
export const getAllDistricts = (): District[] => {
  return INDIAN_STATES_DISTRICTS.flatMap(state => state.districts);
};
